"""
Generate a static Wikipedia-style website from creature data.

Reads the creatures.json manifest and generated images, then produces
a complete static website with species pages, index, and category pages.

Usage:
    python website/generate_site.py --creatures pipeline/output/creatures.json
    python website/generate_site.py --creatures pipeline/output/creatures.json --output website/dist
"""

import argparse
import json
import os
import shutil
from collections import defaultdict
from pathlib import Path

TEMPLATE_DIR = Path(__file__).parent / "templates"
STATIC_DIR = Path(__file__).parent / "static"

HTML_HEAD = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} — Bestiary of the Unreal</title>
    <link rel="stylesheet" href="{css_path}">
</head>
<body>
<header class="site-header">
    <h1><a href="{root}index.html">Bestiary of the Unreal</a></h1>
    <nav>
        <a href="{root}index.html">Main Page</a>
        <a href="{root}categories.html">Categories</a>
        <a href="{root}about.html">About</a>
    </nav>
</header>
<div class="content-wrapper">
"""

HTML_FOOT = """\
</div>
<footer class="site-footer">
    <p>Bestiary of the Unreal — An AI-Generated Encyclopedia of Virtual Creatures</p>
    <p>Images: DDPM trained from scratch | Text: GPT trained from scratch</p>
    <p>Created as part of the Generative AI for Media coursework (2026)</p>
</footer>
</body>
</html>
"""


def render_species_page(creature: dict, all_creatures: list) -> str:
    """Render a single species article page."""
    name = creature["name"]
    cls = creature.get("class", "Unknown")
    habitat = creature.get("habitat", "Unknown")
    size = creature.get("size", "Unknown")
    desc = creature.get("description", "No description available.")
    image = creature.get("image", "")

    # Split description into paragraphs
    paragraphs = [p.strip() for p in desc.split("\n") if p.strip()]
    if not paragraphs:
        paragraphs = [desc]

    desc_html = "\n".join(f"<p>{p}</p>" for p in paragraphs)

    # Find related creatures (same class)
    related = [c for c in all_creatures if c["class"] == cls and c["id"] != creature["id"]][:5]
    related_html = ""
    if related:
        items = "".join(f'<li><a href="{c["id"]}.html">{c["name"]}</a></li>' for c in related)
        related_html = f"<h2>See also</h2>\n<ul>{items}</ul>"

    page = HTML_HEAD.format(title=name, css_path="../static/style.css", root="../")
    page += f"""<article class="article">

<div class="ai-notice">
    <strong>Notice:</strong> This species is entirely fictional. All information on this page,
    including the image and description, was generated by artificial intelligence models
    trained from scratch as part of an academic research project.
</div>

<div class="infobox">
    <div class="infobox-header">{name}</div>
    <div class="infobox-image">
        <img src="../images/{image}" alt="AI-generated image of {name}">
        <div class="caption">AI-generated (DDPM)</div>
    </div>
    <table>
        <tr><th>Class</th><td>{cls}</td></tr>
        <tr><th>Habitat</th><td>{habitat}</td></tr>
        <tr><th>Size</th><td>{size}</td></tr>
        <tr><th>Status</th><td>Virtual</td></tr>
    </table>
</div>

<h1 class="article-title">{name}</h1>
<p class="article-subtitle">From Bestiary of the Unreal, the AI-generated encyclopedia</p>

{desc_html}

<h2>Classification</h2>
<p>This virtual organism is classified under <b>{cls}</b>. Its morphological features were
generated by a Denoising Diffusion Probabilistic Model (DDPM), while its textual description
was produced by a character-level GPT model. Neither model had access to the other's output
during generation.</p>

{related_html}

<div class="categories">
    <span>Categories:</span>
    <span class="category-tag"><a href="../categories.html#{cls}">{cls}</a></span>
    <span class="category-tag"><a href="../categories.html#{habitat}">{habitat}</a></span>
    <span class="category-tag">{size}</span>
</div>

</article>"""
    page += HTML_FOOT
    return page


def render_index_page(creatures: list) -> str:
    """Render the main index page with a grid of all creatures."""
    # Stats
    classes = set(c["class"] for c in creatures)
    habitats = set(c["habitat"] for c in creatures)

    cards = ""
    for c in creatures:
        cards += f"""
        <div class="species-card">
            <a href="species/{c['id']}.html">
                <img src="images/{c['image']}" alt="{c['name']}">
            </a>
            <div class="card-body">
                <h3><a href="species/{c['id']}.html">{c['name']}</a></h3>
                <p>{c['class']} · {c['habitat']}</p>
            </div>
        </div>"""

    page = HTML_HEAD.format(title="Main Page", css_path="static/style.css", root="")
    page += f"""<article class="article">

<h1 class="article-title">Bestiary of the Unreal</h1>
<p class="article-subtitle">An AI-generated encyclopedia of virtual creatures</p>

<div class="ai-notice">
    <strong>Welcome.</strong> This encyclopedia contains <b>{len(creatures)}</b> virtual species,
    each one imagined entirely by artificial intelligence. Every image was generated by a
    <b>Denoising Diffusion Probabilistic Model (DDPM)</b> and every description was written by a
    <b>character-level GPT</b> — both trained from scratch.
</div>

<div class="stats-box">
    <h3>Encyclopedia statistics</h3>
    <dl>
        <dt>Total species</dt><dd>{len(creatures)}</dd>
        <dt>Taxonomic classes</dt><dd>{len(classes)}</dd>
        <dt>Habitats represented</dt><dd>{len(habitats)}</dd>
        <dt>Image model</dt><dd>DDPM (U-Net backbone)</dd>
        <dt>Text model</dt><dd>Character-level GPT (Transformer decoder)</dd>
    </dl>
</div>

<h2>All species</h2>
<div class="species-grid">
{cards}
</div>

</article>"""
    page += HTML_FOOT
    return page


def render_categories_page(creatures: list) -> str:
    """Render category index page."""
    by_class = defaultdict(list)
    by_habitat = defaultdict(list)
    for c in creatures:
        by_class[c["class"]].append(c)
        by_habitat[c["habitat"]].append(c)

    sections = '<h1 class="article-title">Categories</h1>\n'

    sections += "<h2>By taxonomic class</h2>\n"
    for cls in sorted(by_class.keys()):
        items = by_class[cls]
        links = "".join(f'<li><a href="species/{c["id"]}.html">{c["name"]}</a></li>' for c in items)
        sections += f'<div class="category-section" id="{cls}"><h3>{cls} ({len(items)})</h3><ul class="category-list">{links}</ul></div>\n'

    sections += "<h2>By habitat</h2>\n"
    for hab in sorted(by_habitat.keys()):
        items = by_habitat[hab]
        links = "".join(f'<li><a href="species/{c["id"]}.html">{c["name"]}</a></li>' for c in items)
        sections += f'<div class="category-section" id="{hab}"><h3>{hab} ({len(items)})</h3><ul class="category-list">{links}</ul></div>\n'

    page = HTML_HEAD.format(title="Categories", css_path="static/style.css", root="")
    page += f'<article class="article">{sections}</article>'
    page += HTML_FOOT
    return page


def render_about_page() -> str:
    """Render the About page."""
    page = HTML_HEAD.format(title="About", css_path="static/style.css", root="")
    page += """<article class="article">
<h1 class="article-title">About this project</h1>

<h2>What is the Bestiary of the Unreal?</h2>
<p>The Bestiary of the Unreal is a fictional encyclopedia of virtual creatures, generated
entirely by artificial intelligence. It serves as the media artefact for a Level 7 coursework
project in <em>Generative AI for Media</em> at Bournemouth University.</p>

<p>No creature depicted in this bestiary exists in the natural world. Every image was generated
by a <strong>Denoising Diffusion Probabilistic Model (DDPM)</strong>, and every textual description
was written by a <strong>character-level GPT (Generative Pre-trained Transformer)</strong>. Both
models were implemented from scratch in PyTorch and trained on real-world data.</p>

<h2>Technical details</h2>

<h3>Model 1: Image Generation (DDPM)</h3>
<p>A U-Net-based denoising diffusion model trained on animal photographs. The model learns to
generate images by reversing a gradual noising process. Class-conditional generation is
achieved via Classifier-Free Guidance (CFG), allowing control over the general category of
the generated creature.</p>

<h3>Model 2: Text Generation (GPT)</h3>
<p>A character-level Transformer decoder model trained on a corpus of real animal descriptions
(sourced from Wikipedia) and fictional creature entries. The model generates structured species
entries by predicting one character at a time, conditioned on a structured prefix specifying
the creature's taxonomic class, habitat, and size.</p>

<h2>Image–text independence</h2>
<p>Importantly, the image and text for each creature were generated independently. The DDPM
has no knowledge of the textual description, and the GPT has no access to the generated image.
Any apparent correspondence between image and text is coincidental — a limitation discussed
in the accompanying critical reflective paper.</p>

<h2>Ethical statement</h2>
<p>All training data was sourced from publicly available datasets and Wikipedia content under
open licences. No real animals were harmed or exploited. The generated content is clearly
labelled as AI-generated to prevent misinformation. This project is intended for academic
research purposes only.</p>

</article>"""
    page += HTML_FOOT
    return page


def build_site(creatures_path: str, output_dir: str):
    """Build the complete static website."""
    print(f"Loading creatures from {creatures_path}...")
    creatures = json.load(open(creatures_path, "r", encoding="utf-8"))
    print(f"  {len(creatures)} creatures loaded")

    out = Path(output_dir)

    # Create directories
    (out / "species").mkdir(parents=True, exist_ok=True)
    (out / "images").mkdir(exist_ok=True)
    (out / "static").mkdir(exist_ok=True)

    # Copy static assets
    for f in STATIC_DIR.iterdir():
        shutil.copy2(f, out / "static" / f.name)

    # Copy creature images
    images_src = Path(creatures_path).parent / "images"
    if images_src.exists():
        for img in images_src.iterdir():
            shutil.copy2(img, out / "images" / img.name)
        print(f"  Copied {len(list(images_src.iterdir()))} images")

    # Generate pages
    print("Generating pages...")
    index_html = render_index_page(creatures)
    (out / "index.html").write_text(index_html, encoding="utf-8")

    categories_html = render_categories_page(creatures)
    (out / "categories.html").write_text(categories_html, encoding="utf-8")

    about_html = render_about_page()
    (out / "about.html").write_text(about_html, encoding="utf-8")

    for creature in creatures:
        species_html = render_species_page(creature, creatures)
        (out / "species" / f"{creature['id']}.html").write_text(species_html, encoding="utf-8")

    print(f"\nSite built at: {output_dir}/")
    print(f"  index.html — Main page with {len(creatures)} creatures")
    print(f"  categories.html — Browse by class and habitat")
    print(f"  about.html — Project description")
    print(f"  species/ — {len(creatures)} individual creature pages")
    print(f"\nOpen {out / 'index.html'} in a browser to view.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Bestiary website")
    parser.add_argument("--creatures", type=str, default="pipeline/output/creatures.json")
    parser.add_argument("--output", type=str, default="website/dist")
    args = parser.parse_args()
    build_site(args.creatures, args.output)
